

# Модели телефонов, выпущенные от 2022 года и позже
HPV_PHONE_MODEL = [

    'Xiaomi Redmi K60 Pro',
    'Realme C33',
    'Realme Pad 2',
    'Realme Note 50',
    'Realme GT Neo 3T',
    'Xiaomi Redmi Pad Pro',
    'Realme Q5 Pro',
    'Realme 10 Pro',
    'Xiaomi Pad 6 Max 14',
    'Infinix Hot 11s',
    'Xiaomi Redmi A3',
    'Xiaomi Redmi Turbo 3',
    'Xiaomi Redmi Pad SE',
    'Infinix Hot 40 Pro',
    'Realme C65',
    'Xiaomi Redmi Note 11T Pro',
    'Xiaomi 12T',
    'Realme 12 Pro+',
    'Infinix Hot 12',
    'Realme Q5i',
    'Realme V25',
    'Xiaomi Redmi K70 Ultra',
    'Xiaomi 14 Pro',
    'Xiaomi Redmi 12',
    'Xiaomi Redmi Note 12 Turbo',
    'Infinix Smart 7',
    'Infinix Smart 8 Plus',
    'Xiaomi Mix Fold 4',
    'Xiaomi Civi 4 Pro',
    'Xiaomi Redmi Note 11 Pro',
    'Xiaomi Redmi Note 12S',
    'Realme C53',
    'Xiaomi Redmi Note 13 Pro',
    'Realme GT 6T',
    'Realme C67',
    'Xiaomi Poco F6 Pro',
    'Xiaomi Mix Flip',
    'Xiaomi Redmi K70 Pro',
    'Xiaomi 11i HyperCharge',
    'Infinix Hot 30i',
    'Realme 12 Lite',
    'Realme 9i',
    'Infinix Smart 8',
    'Realme 10',
    'Xiaomi Civi 1S',
    'Infinix Note 30',
    'Realme 13 Pro+',
    'Xiaomi Redmi 10A',
    'Xiaomi Poco M5s',
    'Realme GT5 Pro',
    'Infinix Zero',
    'Xiaomi 12S Pro',
    'Xiaomi Redmi Note 12',
    'Realme Narzo 50A Prime',
    'Xiaomi Redmi 12C',
    'Infinix Note 12i',
    'Xiaomi 13 Lite',
    'Xiaomi Poco M6 Plus',
    'Samsung Galaxy S22 Ultra',
    'Xiaomi 14 Civi',
    'Xiaomi Redmi A2',
    'Xiaomi Poco M4',
    'Xiaomi Poco M4 Pro',
    'Xiaomi Redmi 11 Prime',
    'Infinix Note 40',
    'Xiaomi Redmi 10 Power',
    'Xiaomi Poco C55',
    'Infinix Zero 30',
    'Xiaomi Redmi K40S',
    'Xiaomi Poco C65',
    'Xiaomi Redmi Note 11E',
    'Xiaomi Poco M6 Pro',
    'Xiaomi Pad 6S Pro 12.4',
    'Xiaomi Poco X4 GT',
    'Realme GT Neo 3',
    'Realme 11 Pro',
    'Realme 10s',
    'Infinix Note 40 Pro',
    'Realme C63',
    'Xiaomi Redmi Note 12 Pro',
    'Infinix Hot 30 Play',
    'Realme Narzo 50i Prime',
    'Xiaomi 12S Ultra',
    'Infinix Hot 40i',
    'Realme C30s',
    'Realme Pad Mini',
    'Infinix Smart 8 Pro',
    'Xiaomi Redmi 10 2022',
    'Xiaomi Redmi K60E',
    'Xiaomi 13T Pro',
    'Xiaomi Mix Fold 2',
    'Realme C35',
    'Infinix Note 12 Pro',
    'Xiaomi 12 Lite',
    'Infinix Hot 12 Play',
    'Xiaomi Poco C50',
    'Xiaomi 11i',
    'Realme Narzo 50',
    'Xiaomi 13T',
    'Xiaomi Redmi K50 Pro',
    'Realme 9 Pro',
    'Xiaomi 13 Ultra',
    'Xiaomi Poco M5',
    'Xiaomi Poco F4 GT',
    'Xiaomi Poco F5',
    'Xiaomi Poco F5 Pro',
    'Xiaomi Redmi Note 12T Pro',
    'Xiaomi Redmi Note 11E Pro',
    'Realme V23',
    'Xiaomi Pad 6',
    'Xiaomi Redmi Note 12 Pro Speed',
    'Realme C51s',
    'Realme GT5 240W',
    'Xiaomi Poco F6',
    'Xiaomi Redmi K70E',
    'Realme C30',
    'Xiaomi Redmi A3x',
    'Realme C61',
    'Xiaomi Mix Fold 3',
    'Realme C51',
    'Xiaomi Redmi K60 Ultra',
    'Xiaomi Redmi 10C',
    'Xiaomi Redmi A1',
    'Realme C31',
    'Infinix Note 12',
    'Realme V30',
    'Realme C55',
    'Xiaomi 14 Ultra',
    'Realme GT 6',
    'Xiaomi Poco C61',
    'Xiaomi Redmi K50i',
    'Infinix Hot 12 Pro',
    'Xiaomi Redmi Note 11',
    'Realme Narzo N53',
    'Infinix Smart 7 HD',
    'Xiaomi Redmi Note 11S',
    'Xiaomi Poco X4',
    'Xiaomi Poco X4 Pro',
    'Realme Pad X',
    'Xiaomi Redmi Note 13R',
    'Infinix Smart 8 HD',
    'Xiaomi Poco C51',
    'Infinix Hot 20',
    'Xiaomi Civi 3',
    'Xiaomi Poco F4',
    'Realme V23i',
    'Xiaomi 12T Pro',
    'Xiaomi Redmi 13C',
    'Honor X8B',
    'Honor Magic6 Pro',
    'Honor Magic6 Ultimate',
    'Honor X9b',
    'Honor 200 Lite',
    'Huawei Pura 70 Ultra',
    'Huawei Pura 70 Pro',
    'Huawei Pura 70',
    'Huawei nova 12s',
    'Huawei nova Y72',
    'Xiaomi Redmi Note 10T',
    'Xiaomi POCO X6',
    'Xiaomi POCO X6 Pro',
    'Xiaomi POCO M6 Pro',
    'Xiaomi POCO X5',
    'Xiaomi POCO X5 Pro',
    'Xiaomi POCO C40',
    'Xiaomi POCO M5s',
    'Xiaomi POCO M5',
    'Samsung Galaxy A05',
    'Samsung Galaxy A35',
    'Samsung Galaxy S24',
    'Samsung Galaxy S24+',
    'Samsung Galaxy S24 Ultra',
    'Samsung Galaxy A15',
    'Samsung Galaxy A25',
    'Samsung Z Flip5',
    'Samsung Galaxy A05s',
    'Samsung Galaxy A24',
    'Samsung Galaxy A14',
    'Samsung Galaxy S23 FE',
    'Samsung Galaxy Z Fold5',
    'Samsung Galaxy A34',
    'Samsung Galaxy M54',
    'Samsung Galaxy A54',
    'Samsung Galaxy S23+',
    'Samsung Galaxy S23',
    'Samsung Galaxy S23 Ultra',
    'Samsung Galaxy A03',
    'Samsung Galaxy A04',
    'Samsung Galaxy XCover6 Pro',
    'Samsung Galaxy A13',
    'Samsung Galaxy A23',
    'Samsung Galaxy M23',
    'Samsung Galaxy A33',
    'Samsung Galaxy A73',
    'Samsung Galaxy A53',
    'Samsung Galaxy Z Fold4',
    'Samsung Galaxy S22',
    'Samsung Galaxy S22+',
    'Samsung S21 FE',
    'vivo X100 Ultra',
    'vivo V30e',
    'vivo V30 lite',
    'vivo X100',
    'vivo Y27s',
    'vivo X100 Pro',
    'vivo V29e',
    'vivo V29',
    'vivo Y36',
    'vivo V27',
    'vivo V27e',
    'vivo X Note',
    'vivo X80 Pro',
    'vivo T1',
    'vivo X90 Pro',
    'vivo X90 Pro+',
    'vivo V25 Pro',
    'vivo Y35',
    'vivo V25',
    'vivo v23e',
    'vivo v23',
    'OPPO Reno11',
    'OPPO Find X7 Ultra',
    'OPPO Find X7',
    'OPPO Find N2'

]

